#pragma config(Sensor, in1,    analog1,        sensorAnalog)
#pragma config(Sensor, dgtl6,  limit,          sensorDigitalIn)
#pragma config(Sensor, dgtl10, digital10,      sensorDigitalOut)
#pragma config(Sensor, dgtl11, digital11,      sensorDigitalOut)
#pragma config(Sensor, dgtl12, digital12,      sensorDigitalOut)
#pragma config(Motor,  port1, rightMotor,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10, leftMotor,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "gotobeacon.c"
#include "arm.c"


task main() {
	bool foundRed = false;
	bool foundGreen = false;

	freq = 0; // 0 = 1 khz (red)
	ambient_level = 200;
	slow_level = 5000;
	stop_level = 6000;
	expose_time = 5;
	steer_sensitivity = 20;
	forward_speed = -100;
	slow_speed = -25;
	spin_speed = -50;
	SensorValue[digital10] = freq;

	// state 1: find Red Beacon
	while (!foundRed) {
		ReadPD();
		Find_max();
		Move();

		if (SensorValue[limit] == 0) {
			motor[port1] = 0;
			motor[port10] = 0;
			foundRed = true;
			wait1Msec(10000);

			while (PD_sum > ambient_level) {
				armDown();
				wait1Msec(500);
				armUp();
				wait1Msec(500);
			}
		}
	}

	freq = 1; // 1 = 10 khz (green)
	while (!foundGreen) {
		ReadPD();
		Find_max();
		Move();
	}

	// run escape.c
}